// Code generated by schema/generator.go from schema.yaml. DO NOT EDIT.

package dgraph

// SchemaDQL is the Dgraph schema generated from internal/schema/schema.yaml.
// Use InitializeSchema in client.go to inject this into Dgraph at startup.
const SchemaDQL = `
# ----- Competitor -----
Competitor.company_name: string @index(exact) .
Competitor.founded_date: dateTime @index(hour) .
Competitor.funding_stage: string @index(hash) .
Competitor.headquarters: string .
Competitor.team_size: int .
Competitor.threat_level: int .
Competitor.website: string .
Competitor.competes_with: [uid] @reverse .
Competitor.develops: [uid] @reverse .

# ----- Feature -----
Feature.availability: bool .
Feature.category: string @index(hash) .
Feature.description: string .
Feature.evidence_url: string .
Feature.feature_name: string @index(exact) .
Feature.last_updated: dateTime @index(hour) .
Feature.maturity: int .
Feature.part_of: uid @reverse .

# ----- MarketEvent -----
MarketEvent.confidence: float .
MarketEvent.description: string .
MarketEvent.event_date: dateTime @index(hour) .
MarketEvent.event_type: string @index(hash) .
MarketEvent.impact: string @index(hash) .
MarketEvent.source_url: string .

# ----- PricingTier -----
PricingTier.billing_model: string @index(hash) .
PricingTier.currency: string @index(hash) .
PricingTier.last_updated: dateTime @index(hour) .
PricingTier.limitations: string .
PricingTier.price: float .
PricingTier.target_segment: string .
PricingTier.tier_name: string .

# ----- Product -----
Product.category: string @index(hash) .
Product.core_tech: string .
Product.description: string .
Product.launch_date: dateTime @index(hour) .
Product.product_name: string @index(term) .
Product.review_count: int .
Product.user_rating: float .
Product.belongs_to: uid @reverse .
Product.has_pricing: [uid] @reverse .
Product.offers_feature: [uid] @reverse .

# ----- TechComponent -----
TechComponent.architecture: string @index(hash) .
TechComponent.component_name: string .
TechComponent.github_stars: int .
TechComponent.last_commit: dateTime @index(hour) .
TechComponent.open_source: bool .
TechComponent.technology: string .

# ----- UserSegment -----
UserSegment.core_pain_points: [string] .
UserSegment.description: string .
UserSegment.satisfaction_score: float .
UserSegment.segment_name: string .
UserSegment.typical_use_cases: [string] .

# ----- types -----
type Competitor {
    Competitor.company_name
    Competitor.founded_date
    Competitor.funding_stage
    Competitor.headquarters
    Competitor.team_size
    Competitor.threat_level
    Competitor.website
    Competitor.competes_with
    Competitor.develops
}

type Feature {
    Feature.availability
    Feature.category
    Feature.description
    Feature.evidence_url
    Feature.feature_name
    Feature.last_updated
    Feature.maturity
    Feature.part_of
}

type MarketEvent {
    MarketEvent.confidence
    MarketEvent.description
    MarketEvent.event_date
    MarketEvent.event_type
    MarketEvent.impact
    MarketEvent.source_url
}

type PricingTier {
    PricingTier.billing_model
    PricingTier.currency
    PricingTier.last_updated
    PricingTier.limitations
    PricingTier.price
    PricingTier.target_segment
    PricingTier.tier_name
}

type Product {
    Product.category
    Product.core_tech
    Product.description
    Product.launch_date
    Product.product_name
    Product.review_count
    Product.user_rating
    Product.belongs_to
    Product.has_pricing
    Product.offers_feature
}

type TechComponent {
    TechComponent.architecture
    TechComponent.component_name
    TechComponent.github_stars
    TechComponent.last_commit
    TechComponent.open_source
    TechComponent.technology
}

type UserSegment {
    UserSegment.core_pain_points
    UserSegment.description
    UserSegment.satisfaction_score
    UserSegment.segment_name
    UserSegment.typical_use_cases
}

`
